# Simple CI/CD pipeline for building and pushing Docker image to GHCR
#
# This workflow builds the Docker image and pushes it to GitHub Container Registry (GHCR)
# on every push to the main branch.

name: Build and Push Docker image

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_url: ${{ steps.export_image_url.outputs.image_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Generate timestamp tag
        id: timestamp
        run: echo "tag=$(date +'%Y-%m-%d_%H-%M')" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.timestamp.outputs.tag }}

      - name: Export Docker image URL
        id: export_image_url
        run: |
          echo "image_url=ghcr.io/${{ github.repository }}:${{ steps.timestamp.outputs.tag }}" >> "$GITHUB_OUTPUT"


  tf-plan:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials (assume role)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.DEPLOYER_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=quotes-database.tfstate" \
            -backend-config="region=${{ vars.AWS_REGION }}"

      - name: Terraform Plan
        working-directory: infra
        env:
          TF_LOG: debug
        run: terraform plan
